### ISSUE TITLE
Python Modules

### ISSUE THREAD

**Issue by obriencole11** [BWoodward95/RigBox#2]
This entire project should be a python module. To create a python module just put all these scripts in a directory named something like `rigbox` (lowercase is preferred for modules) and add an empty `__init__.py` file to it. This means you can remove the `RigBox_` prefix from each script and instead you can just import scripts like so:

```
from rigbox import main
main.do_something()
```

Also while you're at it I'd recommend making all the script names lowercase. Its a minor note, but its a [PEP8](https://peps.python.org/pep-0008/#package-and-module-names) thing. Typically when people see uppercase objects they will assume they're classes.

**Comment by BWoodward95** [comment]
Will do, thanks for the advice!
